name: Test and Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Build tests
        run: |
          cargo test --all-features --no-run

      - name: Run unit tests
        run: |
          cargo test --all-features
        env:
          RUST_BACKTRACE: 1

  package:
    runs-on: ubuntu-latest
    environment: khonsu.dev
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build executable
        run: |
          cargo build --bin dossier --release --all-features

      - uses: actions/upload-artifact@v2
        with:
          name: dossier
          path: target/release/dossier

  deploy:
    runs-on: ubuntu-latest
    environment: khonsu.dev
    timeout-minutes: 30
    needs: [package, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dossier
      
      - name: Gather artifacts 
        run: |
          chmod a+x dossier

      - name: Configure SSH 
        run: |
          mkdir ~/.ssh
          chmod 0700 ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/deploy_key
          chmod 0600 ~/.ssh/deploy_key
          ssh-keyscan -H ams01.khonsu.dev >> ~/.ssh/known_hosts
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          
      - name: Deploy
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" dossier dossier@ams01.khonsu.dev:
          ssh -i ~/.ssh/deploy_key dossier@ams01.khonsu.dev sudo /usr/bin/systemctl restart dossier.service
